### ISSUE TITLE
Trazer todo ``Gerador de dataset`` para este projeto

### ISSUE THREAD

**Issue by Juliano-rb** [Juliano-rb/tweets-sentiment-classification-system#1]
- [x] UI: https://github.com/Juliano-rb/tweet-dataset-creator-client.
- [x] Evaluate Service: https://github.com/Juliano-rb/tweet-dataset-creator-api
- [x] Dataset-tools: https://github.com/Juliano-rb/fetch-tweets-to-mongodb
